
server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bp_exercise
    username: root
    password: jhloli0403

environment:
  clienteURL: http://localhost:8080